### ISSUE TITLE
Eh, doesn't work 1.12?

### ISSUE THREAD

**Issue by LegitSoulja** [ysl3000/WorldBorderAPI1.8-#5]
Have you tested 1.12? Can't get a border around a player.

**Comment by LegitSoulja** [comment]
Ah nvm sorry. Using wrong methods. It was spawning at the player spawn location.

**Comment by J-Vernay** [comment]
I don't know where I can ask it, but as a new java developer, how can I add this library to my plugin ?

**Comment by ysl3000** [comment]
@J-Vernay Just compile the plugin using maven and add it as a maven dependency to your plugin.
If you do not want to use maven in your plugin just add the built jar as a library.
